name: Cleanup release and tags

on:
  schedule:
    - cron: "15 2 * * *"
  workflow_dispatch:
    inputs:
      older_than_days:
        description: "Delete releases/tags older than this many days"
        required: true
        default: "30"
      dry_run:
        description: "Dry run only"
        required: true
        default: "true"

jobs:
  cleanup:
    permissions:
      contents: write
    uses: elegant-software/elegant-ci-cd-pipeline/.github/workflows/cleanup-release-tags.yml@1f506dd1bd3686d6e31b3169977b2b672ff38a1a
    with:
      older_than_days: ${{ fromJSON(inputs.older_than_days || '30') }}
      dry_run: ${{ fromJSON(inputs.dry_run || 'true') }}
      delete_drafts: true
      delete_prereleases: true
