name: Cleanup old/failed workflow

on:
  schedule:
    - cron: "15 2 * * *"
  workflow_dispatch:
    inputs:
      older_than_days:
        description: "Delete releases/tags older than this many days"
        required: true
        default: "14"
      dry_run:
        description: "Dry run only"
        required: true
        default: "true"

jobs:
  cleanup:
    permissions:
      actions: write
      contents: write
    uses: elegant-software/elegant-ci-cd-pipeline/.github/workflows/cleanup-github-workflows.yml@1f506dd1bd3686d6e31b3169977b2b672ff38a1a
    with:
        older_than_days: ${{ fromJSON(inputs.older_than_days || '14') }}
        dry_run: ${{ fromJSON(inputs.dry_run || 'true') }}
