name: Release Notes (on main branch merge)

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  release-notes:
    if: ${{ github.event.pull_request.merged == true }}
    uses: elegant-software/elegant-ci-cd-pipeline/.github/workflows/release-notes.yml@1f506dd1bd3686d6e31b3169977b2b672ff38a1a
